# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Live' do
  use_frameworks!
    pod 'Alamofire', '~> 4.1.0'
    pod 'Kingfisher', '~> 3.2.1'
    pod 'ProtocolBuffers-Swift', '~> 4.0.1'
    pod 'LFLiveKit', '2.6'
    pod 'PKHUD', '~> 5.0.0'
end
